name       : bluez
version    : '5.50'
release    : 25
source     :
    - https://www.kernel.org/pub/linux/bluetooth/bluez-5.50.tar.xz : 5ffcaae18bbb6155f1591be8c24898dc12f062075a40b538b745bfd477481911
license    :
    - GPL-2.0
    - LGPL-2.1
component  : system.utils
summary    : Official Linux Bluetooth protocol stack.
description: |
    The Bluetooth wireless technology is a worldwide specification for a small-form factor, low-cost radio solution that provides links between mobile computers, mobile phones, other portable handheld devices, and connectivity to the Internet. The specification is developed, published and promoted by the Bluetooth Special Interest Group (SIG).f BlueZ provides support for the core Bluetooth layers and protocols. It is flexible, efficient and uses a modular implementation.
builddeps  :
    - pkgconfig(libical)
    - cups-devel
setup      : |
    %apply_patches
    %reconfigure --enable-cups \
                 --enable-tools \
                 --enable-library \
                 --enable-sixaxis \
                 --enable-nfc \
                 --enable-experimental
build      : |
    %make
install    : |
    %make_install
    %make DESTDIR=%installroot% \
            install-includeHEADERS \
            install-libLTLIBRARIES \
            install-pkgconfigDATA
    install -D -m 00755 src/main.conf $installdir/usr/share/defaults/bluetooth/main.conf
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/bluetooth.target.wants
    ln -sv bluetooth.service  $installdir/usr/lib/systemd/system/dbus-org.bluez.service
    ln -sv ../bluetooth.service  $installdir/usr/lib/systemd/system/bluetooth.target.wants/bluetooth.service
    ln -sv obex.service $installdir/usr/lib/systemd/user/dbus-org.bluez.obex.service
