name       : bluez
version    : '5.55'
release    : 28
source     :
    - https://mirrors.edge.kernel.org/pub/linux/bluetooth/bluez-5.55.tar.xz : 8863717113c4897e2ad3271fc808ea245319e6fd95eed2e934fae8e0894e9b88
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : system.utils
summary    : Official Linux Bluetooth protocol stack.
description: |
    The Bluetooth wireless technology is a worldwide specification for a small-form factor, low-cost radio solution that provides links between mobile computers, mobile phones, other portable handheld devices, and connectivity to the Internet. The specification is developed, published and promoted by the Bluetooth Special Interest Group (SIG).f BlueZ provides support for the core Bluetooth layers and protocols. It is flexible, efficient and uses a modular implementation.
builddeps  :
    - pkgconfig(libical)
    - cups-devel
setup      : |
    %apply_patches
    %reconfigure --enable-cups \
                 --enable-experimental \
                 --enable-hid2hci \
                 --enable-library \
                 --enable-nfc \
                 --enable-sixaxis \
                 --enable-tools
build      : |
    %make
install    : |
    %make_install
    install -D -m 00755 src/main.conf $installdir/usr/share/defaults/bluetooth/main.conf
    install -D -d -m 00755 $installdir/usr/lib/systemd/system/bluetooth.target.wants
    ln -sv bluetooth.service  $installdir/usr/lib/systemd/system/dbus-org.bluez.service
    ln -sv ../bluetooth.service  $installdir/usr/lib/systemd/system/bluetooth.target.wants/bluetooth.service
    ln -sv obex.service $installdir/usr/lib/systemd/user/dbus-org.bluez.obex.service
