name       : bluez
version    : '5.45'
release    : 12
source     :
    - https://www.kernel.org/pub/linux/bluetooth/bluez-5.45.tar.xz : 4cacb00703a6bc149cb09502257d321597d43952374a16f3558766ffa85364e9
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : Official Linux Bluetooth protocol stack.
component  : system.utils
description: |
    The Bluetooth wireless technology is a worldwide specification for a small-form factor, low-cost radio solution that provides links between mobile computers, mobile phones, other portable handheld devices, and connectivity to the Internet. The specification is developed, published and promoted by the Bluetooth Special Interest Group (SIG).f BlueZ provides support for the core Bluetooth layers and protocols. It is flexible, efficient and uses a modular implementation.
builddeps  :
    - pkgconfig(libical)
    - cups-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Make-main.conf-stateless.patch
    %reconfigure --enable-cups \
               --enable-tools \
               --enable-library \
               --enable-sixaxis \
               --enable-experimental
build      : |
    %make
install    : |
    %make_install
    %make DESTDIR=%installroot% \
            install-includeHEADERS \
            install-libLTLIBRARIES \
            install-pkgconfigDATA
    install -Dm00755 src/main.conf $installdir/usr/share/defaults/bluetooth/main.conf
    mkdir -p $installdir/%libdir%/systemd/system/bluetooth.target.wants
    ln -sv %libdir%/systemd/system/bluetooth.service  $installdir/%libdir%/systemd/system/dbus-org.bluez.service
    ln -sv %libdir%/systemd/system/bluetooth.service  $installdir/%libdir%/systemd/system/bluetooth.target.wants/bluetooth.service
